images:
  -
    image: 
      - ghcr.io/shyim/shopware-docker/5/apache
    buildTags: [ 'apache' ]
    dockerFile: apache/Dockerfile
    context: apache
    variables:
      APP_DOCUMENT_ROOT: '/var/www/html'
    templates:
      apache/Dockerfile.twig: apache/Dockerfile
      apache/classic-vhost.conf: apache/rootfs/etc/apache2/conf.d/vhost.conf
    tags:
      php80:
        phpVersion: '8.0'
        phpVersionNumeric: 80
  -
    image: 
      - ghcr.io/shyim/shopware-docker/6/apache
    buildTags: [ 'apache' ]
    dockerFile: apache/Dockerfile
    context: apache
    variables:
      APP_DOCUMENT_ROOT: '/var/www/html/public'
    templates:
      apache/Dockerfile.twig: apache/Dockerfile
      apache/platform-vhost.conf: apache/rootfs/etc/apache2/conf.d/vhost.conf
    tags:
      php74:
        phpVersion: '8.0'
        phpVersionNumeric: 80