images:
  -
    image: 
      - ghcr.io/shyim/shopware-docker/5/nginx-production
    buildTags: [ 'production' ]
    dockerFile: nginx/Dockerfile
    context: nginx 
    templates:
      nginx/Dockerfile.twig: nginx/Dockerfile
      nginx/10-classic.conf: nginx/rootfs/etc/nginx/sites-enabled/www.conf
    variables:
      production: true
      APP_DOCUMENT_ROOT: '/var/www/html'
    tags:
      php74:
        phpVersion: '7.4'
        phpVersionNumeric: 74
      php80:
        phpVersion: '8.0'
        phpVersionNumeric: 80
  -
    image: 
      - ghcr.io/shyim/shopware-docker/6/nginx-production
    buildTags: [ 'production' ]
    dockerFile: nginx/Dockerfile
    context: nginx 
    templates:
      nginx/Dockerfile.twig: nginx/Dockerfile
      nginx/10-platform.conf: nginx/rootfs/etc/nginx/sites-enabled/www.conf
    variables:
      production: true
      APP_DOCUMENT_ROOT: '/var/www/html/public'
    tags:
      php74:
        phpVersion: '7.4'
        phpVersionNumeric: 74
      php80:
        phpVersion: '8.0'
        phpVersionNumeric: 80